version: 2
jobs:
  test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: npm run ci
  publish:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: npm run ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm run release
workflows:
  version: 2
  test_builds:
    jobs:
      - test
  tagged_builds:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
